### ISSUE TITLE
Code running problems

### ISSUE THREAD

**Issue by zhangyi-student** [jingjin25/LFASR-geometry#3]
First of all, congratulations on your article being included by AAAI. The following error occurred when I reproduced your code.What code needs to be changed？

**Comment by zhangyi-student** [comment]
ind_source, input, target_y, lfi_ycbcr = batch[0], batch[1], batch[2].numpy(), batch[3].numpy()
**IndexError: list index out of range**

**Comment by jingjin25** [comment]
@zhangyi-student  Hi, could you provide more details about your running error? I have tested the code again, and everything went well.

**Comment by zhangyi-student** [comment]
Thank you. I have solved this problem. I need to use Matlab to process the data set
