### ISSUE TITLE
Performance of the pre-trained model

### ISSUE THREAD

**Issue by Aithusa1113** [jingjin25/LFASR-geometry#7]
Hi, excellent work!
I test the pre-trained model "HCI_2x2-7x7.pth" on four LF data in  HCI_new, including bedroom, bicycle, herbs, and dishes. But I got :
===> test
loaded model ./pretrained_model/HCI_2x2-7x7.pth
testing LF 0
psnr: 37.54, ssim: 0.948
testing LF 1
psnr: 30.84, ssim: 0.915
testing LF 2
psnr: 32.22, ssim: 0.867
testing LF 3
psnr: 28.56, ssim: 0.914
Comparing to your reported results in the paper, it is much lower performance. Do you have any idea what is wrong with the testing?

Looking forward to your reply!

**Comment by jingjin25** [comment]
@Aithusa1113 

Hi, maybe the PyTorch version you used is higher than 1.1?

**Comment by Aithusa1113** [comment]
> @Aithusa1113
> 
> Hi, maybe the PyTorch version you used is higher than 1.1?
Yes, torch.version==1.8.0. Is it about the default setting of "align_corners" in F.grid_sample?

**Comment by jingjin25** [comment]
@Aithusa1113 

Yes. You can simply set align_corners=True for F.grid_sample in model_for_test.py and model_utility.py. Then you could get the same results as those in the paper.

**Comment by Aithusa1113** [comment]
It works! Thanks a lot!
