### ISSUE TITLE
Cannot get the correct result on HCI-old

### ISSUE THREAD

**Issue by li-fang** [jingjin25/LFASR-geometry#9]
Hi Dr. Jin, thanks for sharing your great work. I tried your model on HCI and got the result as good as listed in your paper. But I cannot get the correct result on HCI-old. Could you please provide a demo on HCI-old? Thanks in advance!

**Comment by jingjin25** [comment]
@li-fang 

HI, I think the problem might be caused by the data loader for HCI old, so I just upload the matlab code for generating test data from HCI old.  Please try again.

**Comment by li-fang** [comment]
> @li-fang
> 
> HI, I think the problem might be caused by the data loader for HCI old, so I just upload the matlab code for generating test data from HCI old. Please try again.

It works. Thank you!
